### ISSUE TITLE
Can't connect to Elfin EW11a

### ISSUE THREAD

**Issue by mschae** [nathanmarlor/foxess_modbus#272]
## Version of the custom_component

v1.5.2

## Configuration

```yaml
Add your logs here.
```

## Describe the bug

When attempting to connect to the adapter for the first time I get the following error message:

> Unable to connect to your adapter. Ensure that the adapter is properly configured (see the setup link above) and the connection details are correct, then try again. Details: Modbus Error: [Connection] ModbusTcpClient(10.112.1.214:502): Connection unexpectedly closed 1.0967254638671875e-05 seconds into read of 8 bytes without response from unit before it closed connection.

The adapter seems to receive the "init" frames and it looks like it can talk to the inverter but closes the connection prematurely: 
<img width="747" alt="Bildschirm­foto 2023-05-23 um 13 30 26" src="https://github.com/nathanmarlor/foxess_modbus/assets/473241/de16f837-8966-4f68-95f5-d255bb7c0d82">

## Debug log

```text

Logger: custom_components.foxess_modbus.modbus_controller
Source: custom_components/foxess_modbus/modbus_client.py:160 
Integration: FoxESS - Modbus ([documentation](https://github.com/nathanmarlor/foxess_modbus), [issues](https://github.com/nathanmarlor/foxess_modbus/issues)) 
First occurred: 12:05:17 (35 occurrences) 
Last logged: 13:33:27

Autodetect: failed to connect to (tcp://10.112.1.214:502)
Autodetect: failed to connect to (tcp://10.222.0.213:502)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/tcp.py", line 309, in recv
    ready = select.select([self.socket], [], [], end - time_)
ValueError: filedescriptor out of range in select()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/foxess_modbus/modbus_controller.py", line 332, in autodetect
    await client.read_registers(
  File "/config/custom_components/foxess_modbus/modbus_client.py", line 73, in read_registers
    response = await self._async_pymodbus_call(
  File "/config/custom_components/foxess_modbus/modbus_client.py", line 160, in _async_pymodbus_call
    result = await self._hass.async_add_executor_job(call, *args)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 100, in read_holding_registers
    return self.execute(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/base.py", line 192, in execute
    return self.transaction.execute(request)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 159, in execute
    response, last_exception = self._transact(
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 306, in _transact
    result = self._recv(response_length, full)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/transaction.py", line 341, in _recv
    read_min = self.client.framer.recvPacket(min_size)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/framer/__init__.py", line 53, in recvPacket
    return self.client.recv(size)  # pylint: disable=no-member
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/tcp.py", line 311, in recv
    return self._handle_abrupt_socket_close(size, data, time.time() - time_)
  File "/usr/local/lib/python3.10/site-packages/pymodbus/client/tcp.py", line 363, in _handle_abrupt_socket_close
    raise ConnectionException(msg)
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] ModbusTcpClient(10.112.1.214:502): Connection unexpectedly closed 3.62396240234375e-05 seconds into read of 8 bytes without response from unit before it closed connection
```

**Comment by canton7** [comment]
Moving to a discussion, as this is support rather than an issue with the integration
