### ISSUE TITLE
Errors after upgrading to v1.1.0

### ISSUE THREAD

**Issue by canton7** [nathanmarlor/foxess_modbus#42]
## Version of the custom_component

v1.1.0

## Configuration

N/A

## Describe the bug

I just upgraded to v1.1.0 (thanks for releasing that), and HA shows me:

![image](https://user-images.githubusercontent.com/568104/225345605-3944b4af-c4fe-4cb5-9434-0a0862a73796.png)

The relevant errors are:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/foxess_modbus/sensor.py", line 24, in async_setup_entry
    inverters = hass.data[DOMAIN][entry.entry_id][INVERTERS]
KeyError: '9266abd35104a5df58e78c7bd97b1fc2'
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/foxess_modbus/binary_sensor.py", line 23, in async_setup_entry
    inverters = hass.data[DOMAIN][entry.entry_id][INVERTERS]
KeyError: '9266abd35104a5df58e78c7bd97b1fc2'
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/foxess_modbus/__init__.py", line 69, in async_setup_entry
    del data[CONFIG_SAVE_TIME]
KeyError: 'save_time'
```

It looks like some recent changes are making assumptions about what configuration data is present?

**Comment by canton7** [comment]
Interestingly I can replicate at least the first two errors in my dev environment by downgrading to 1.0.4

**Comment by nathanmarlor** [comment]
@canton7 the config flow has completely changed - delete and re-add the integration please! :)
